// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQuH4hO2DE6PcbQm6QRd28A3BLAFuGyfo',
    appId: '1:510264322044:android:926cc07e31d08dd81f7479',
    messagingSenderId: '510264322044',
    projectId: 'my-vistor',
    databaseURL: 'https://my-vistor-default-rtdb.firebaseio.com',
    storageBucket: 'my-vistor.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZVg5bnredttvVUurP3-HGVISaGrpNGd8',
    appId: '1:510264322044:ios:496cc5055f087b2a1f7479',
    messagingSenderId: '510264322044',
    projectId: 'my-vistor',
    databaseURL: 'https://my-vistor-default-rtdb.firebaseio.com',
    storageBucket: 'my-vistor.firebasestorage.app',
    androidClientId: '510264322044-p1rktuun2gctkisr1bmg71lf87cj2qrq.apps.googleusercontent.com',
    iosClientId: '510264322044-jfnllnftdbbhhe5qnh2vg54go1rudf92.apps.googleusercontent.com',
    iosBundleId: 'com.example.myVisitorAdmin',
  );
}
